[package]
name = "wishbone-tool"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]
edition = "2018"

[dependencies]
bitflags = "1"
byteorder = "1"
clap = "2"

# git = "https://github.com/paritytech/libusb-rs.git"
libusb-sys = { path="libusb-sys" }
# git = "https://github.com/paritytech/libusb-rs.git"
libusb = { path = "libusb-rs" }

rand = "0"

log = "0"
flexi_logger = { version = "0", features = ["colors"] }
# pretty_env_logger  = "0.3"